export enum CandidateStatus {
  NOT_PASS = 'Not Pass',
  PENDING_DOCUMENT = 'Pending for document upload',
  READY_SHORTLIST = 'Ready for shortlist',
  WITHDRAWN_BEFORE_INTERVIEW = 'Withdrawn By Candidate (Before Interview)',
  PENDING_SELECTION = 'Pending BL selection',
  REJECTED_PROFILE = 'BL Reject profile',
  NO_SHOW = 'Candidate no show',
  PASSED_INTERVIEW = 'Pass Interview',
  FAILED_INTERVIEW = 'Fail Interview',
  ON_HOLD = 'On Hold',
  WITHDRAWN_AFTER_INTERVIEW = 'Withdrawn By Candidate (After Interview)',
  OFFER_IN_PROGRESS = 'Offer in progress',
  ACCEPT_OFFER = 'Accept offer',
  DECLINE_OFFER = 'Decline offer',
}
